volumes:
  pg_data_production: {}
  static_volume:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: tanya2222/foodgram_backend5
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_volume:/static
  frontend:
    env_file: .env
    image: tanya2222/foodgram_frontend5
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  infra:
    image: tanya2222/foodgram_infra5
    env_file: .env
    volumes:
      - static_volume:/usr/share/nginx/html
    ports:
      - 8000:80

