volumes:
  pg_data:
  static:
  media:
  redoc:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    image: tanya2222/foodgram-backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/app/static
      - media:/app/media
      - redoc:/app/docs
  frontend:
    env_file: .env
    container_name: foodgram_frontend5
    image: tanya2222/foodgram_frontend5
    volumes:
      - ./frontend/:/app/result_build/
  nginx:
    container_name: foodgram_infra5
    image: nginx:1.25.4-alpine
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
